# Generated by Django 6.0.7 on 2026-07-21 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0003_contactlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название групп')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Группа  контактов',
                'verbose_name_plural': 'Группы контактов',
                'ordering': ('title',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='contactlist',
            name='unique_contact_list_per_owner',
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='contact_groups', to='email_sender.contact', verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_groups', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.RemoveField(
            model_name='contactlist',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='contactlist',
            name='owner',
        ),
        migrations.AddConstraint(
            model_name='contactgroup',
            constraint=models.UniqueConstraint(fields=('owner', 'title'), name='unique_contact_group_per_owner'),
        ),
        migrations.DeleteModel(
            name='ContactList',
        ),
    ]
