# Generated by Django 6.0.7 on 2026-07-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0006_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирована'), ('processing', 'Отправляется'), ('completed', 'Завершена'), ('completed_with_errors', 'Завершена c ошибками'), ('failed', 'Ошибка'), ('canceled', 'Отменена')], default='draft', max_length=25, verbose_name='Статус'),
        ),
    ]
