# Generated by Django 6.0.7 on 2026-07-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0007_alter_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='failed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Ошибок'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sent_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Отправлено '),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего получателей'),
        ),
    ]
