# Generated by Django 6.0.7 on 2026-07-22 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0008_campaign_failed_count_campaign_sent_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата запланированной отправки'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_logs', to='email_sender.contacts', verbose_name='Контакт'),
        ),
    ]
